<div class="hero-unit">
    <h1>Welcome!</h1>
    <p>
        Congratulations! You have successfully installed the sample application for the
        "RESTful Services Made Easy With ZF2" tutorial from PHPBenelux 2013. You 
        are currently running Zend Framework version <?php echo \Zend\Version\Version::VERSION ?>. 
    </p>

    <p>
        A good starting point is <a href="<?php echo 
        $this->url('phpbnl13_status_api/documentation') ?>">the API documentation for 
        the example service</a>.
    </p>
</div>

